- name: Identify if there is a running ASM instance
  environment:
    ORACLE_DB: "ASM"
  shell: |
    ps aux | grep pmon | grep -v grep | grep "$ORACLE_DB" | awk '{print $1}'
  register: ps_asm_owner

- name: successfully fetched ASM data, proceeding with entity config
  block:
    - name: Fetch SID
      environment:
        ORACLE_DB: "ASM"
      shell: |
        cat /etc/oratab | grep -v "^#" | grep -v "N$" | grep "$ORACLE_DB" | head -1 | cut -f1 -d: -s
      register: ps_asm_sid
    - name: Locate grid home for ASM instance
      environment:
        ORACLE_DB: "ASM"
      shell: |
        cat /etc/oratab | grep -v "^#" | grep -v "N$" | grep "$ORACLE_DB" | head -1 | cut -f2 -d: -s
      register: ps_asm_grid_home
    - name: Fetch FQDN of hostname
      shell: |
        hostname -f
      register: hostname_fdqn_asm
    - name: identify primary group for ASM grid user
      shell: |
        id -gn {{ps_asm_owner.stdout}}
      register: id_group_name_asm
    - name: identify primary group for ASM grid user
      shell: |
        id -g {{ps_asm_owner.stdout}}
      register: id_group_id_asm
    - name: set facts for ASM instance
      set_fact:
        oracle_asm_grid_home: "{{ps_asm_grid_home.stdout}}"
        oracle_asm_owner: "{{ps_asm_owner.stdout}}"
        oracle_asm_sid: "{{ps_asm_sid.stdout}}"
        oracle_asm_hostname: "{{hostname_fdqn_asm.stdout}}"
        oracle_asm_group: "{{id_group_name_asm.stdout}}"
        oracle_asm_group_id: "{{id_group_id_asm.stdout}}"
        oracle_asm_exists: yes
    - name: Copy ASM User Creation Scipt to Server
      copy:
        src: "{{role_path}}/files/grantAsmPrivileges.sql"
        dest: "{{ omc_cloudagent_stage_dir }}"
        owner: "{{omc_cloudagent_user}}"
        group: "{{omc_cloudagent_group}}"
        mode: 0777
      tags: install
    - name: "deploy OMC monitoring user on {{ oracle_asm_sid}}"
      environment:
        ORACLE_DB: "{{oracle_asm_sid}}"
        ORAENV_ASK: "NO"
      shell: |
        export PATH=/usr/local/bin:$PATH
        export ORACLE_SID=$(cat /etc/oratab | grep -v "^#" | grep -v "N$" | grep "$ORACLE_DB" | head -1 | cut -f1 -d: -s)
        export ORACLE_HOME=$(cat /etc/oratab | grep -v "^#" | grep -v "N$" | grep "$ORACLE_DB" | head -1 | cut -f2 -d: -s)
        . /usr/local/bin/oraenv
        $ORACLE_HOME/bin/sqlplus -S / as sysdba @grantAsmPrivileges.sql "{{ omc_cloudagent_asm_user }}" "{{ omc_cloudagent_asm_password }}"
      args:
        chdir: "{{ omc_cloudagent_stage_dir }}"
      register: asm_user_deployment
      become: yes
      become_user: "{{oracle_asm_owner}}"
      failed_when:
        - "((asm_user_deployment.rc is defined and asm_user_deployment.rc == 0 and 'ORA-' in asm_user_deployment.stdout) or (asm_user_deployment.rc is defined and asm_user_deployment.rc > 0))"
      run_once: yes
      ignore_errors: yes


  when:
    - ps_asm_owner.stdout is defined
    - ps_asm_owner.stdout != ''
    - ps_asm_owner.rc is defined
    - ps_asm_owner.rc == 0
