---
- name: deploying ASM entities
  block:
    - name: copy ASM credentials JSON to server
      template:
        src: "{{ role_path }}/templates/asm-creds.json.j2"
        dest: "{{ omc_cloudagent_stage_dir }}/asm-creds.json"
        owner: "{{ omc_cloudagent_user }}"
        group: "{{  omc_cloudagent_users_group }}"
        mode: 0755
    - name: copy ASM entity JSON to server
      template:
        src: "{{ role_path }}/templates/asm-entity.json.j2"
        dest: "{{ omc_cloudagent_stage_dir }}/asm-entity.json"
        owner: "{{ omc_cloudagent_user }}"
        group: "{{  omc_cloudagent_users_group }}"
        mode: 0755
    - name: Deploy ASM Entity
      shell: |
        sh {{omc_cloudagent_install_dir}}/agent_inst/bin/omcli add_entity agent {{ omc_cloudagent_stage_dir }}/asm-entity.json -credential_file {{ omc_cloudagent_stage_dir }}/asm-creds.json
      args:
        chdir: "{{ omc_cloudagent_stage_dir }}"
      become: yes
      become_user: "{{omc_cloudagent_user}}"
      run_once: yes
  when:
    - oracle_asm_exists is defined
    - oracle_asm_exists



- name: copy Oracle DB credentials JSON to server
  template:
    src: "{{ role_path }}/templates/oracle-db-creds.json.j2"
    dest: "{{ omc_cloudagent_stage_dir }}/oracle-db-creds.json"
    owner: "{{ omc_cloudagent_user }}"
    group: "{{  omc_cloudagent_users_group }}"
    mode: 0755
- name: copy Oracle DB entity JSON to server
  template:
    src: "{{ role_path }}/templates/oracle-db-entity.json.j2"
    dest: "{{ omc_cloudagent_stage_dir }}/oracle-db-entity.json"
    owner: "{{ omc_cloudagent_user }}"
    group: "{{  omc_cloudagent_users_group }}"
    mode: 0755