---
- name: set basic variables for use in play
  set_fact:
    omc_cloudagent_install_cmd: |
      {{omc_cloudagent_stage_dir}}/AgentInstall.sh \
        TENANT_NAME={{ omc_cloudagent_tenant_name }} \
        AGENT_REGISTRATION_KEY={{ omc_cloudagent_registration_key}} \
        AGENT_BASE_DIRECTORY={{ omc_cloudagent_install_dir }} \
        AGENT_PORT={{ omc_cloudagent_agent_port }} \
        OMC_URL={{ omc_cloudagent_url_endpoint }} \
        GATEWAY_HOST={{ omc_cloudagent_gateway_host }} \
        GATEWAY_PORT={{ omc_cloudagent_gateway_port }} \
        ADDITIONAL_GATEWAYS={{ omc_cloudagent_additional_gateways }} \
        REINSTALL={{ omc_cloudagent_reinstall_agent }}
    omc_cloudagent_user: "{{omc_cloudagent_users.0.username }}"
    omc_cloudagent_group: "{{omc_cloudagent_users.0.group }}"
    omc_cloudagent_software: "cloudagent_linux.x64.zip"
    omc_cloudagent_ulimts: "{{omc_cloudagent_users.0.ulimits }}"
