---
# tasks file for oracle-omc-cloudagent
- name: Set facts about installation
  include_tasks: facts.yml

- name: "download latest cloud agent from public URL"
  get_url:
    url: "{{ omc_cloudagent_software_url }}"
    dest: "{{ role_path }}/files/cloudagent_linux.x64.zip"
  delegate_to: localhost
  become: no

- name: Validate files exist locally
  local_action: stat path="{{ role_path }}/files/cloudagent_linux.x64.zip"
  become: no
  register: ls_omc_cloudagent_image

- include: "{{ role_path }}/tasks/os.yml"

- name: create destination directory
  file:
    dest: "{{ item }}"
    state: directory
    owner: "{{ omc_cloudagent_users.0.username }}"
    group: "{{ omc_cloudagent_users.0.group }}"
  with_items:
    - "{{ omc_cloudagent_stage_dir }}"
    - "{{ omc_cloudagent_install_dir }}"
  become: yes
  become_user: root

- name: uploading and unarchive installer
  unarchive:
    src: "{{ role_path }}/files/cloudagent_linux.x64.zip"
    dest: "{{ omc_cloudagent_stage_dir }}"
  tags: install
