---
# tasks file for oracle-omc-cloudagent
- name: Set facts about supplied information
  include_tasks: set_facts.yml
  tags:
    - oem
    - installation
    - set_facts

- name: Check for cloud agent files.
  local_action: stat path="{{ role_path }}/files/cloudagent_linux.x64_{{ omc_agent_version }}.zip"
  become: false
  register: ls_omc_cloudagent_image

- include: "{{ role_path }}/tasks/os.yml"

- name: creating temporary directory
  file:
    path: "{{ omc_agent_tmp_install_dir }}"
    state: directory
    owner: "{{ omc_agent_user }}"
    group: "{{ omc_agent_group }}"

- name: Installing dependencies
  yum:
    name: "{{ omc_cloudagent_required_packages }}"
    state: present
  when: ansible_os_family == 'RedHat'
