---
# tasks file for oracle-omc-cloudagent
- name: Set basic facts about OMC installation
  include_tasks: facts.yml
- name: Configure OS prerequisites for OMC Cloud Agent
  include_tasks: os.yml
- name: Configure OS users & groups required of OMC
  include_tasks: user.yml
- name: Download latest OMC agent installation file
  include_tasks: fetch.yml
- name: Install OMC Agent
  include_tasks: install.yml
- name: "Execute Agent Post Install Steps"
  include_tasks: post-install.yml
- name: "Deploying to running ASM instance"
  include_tasks: asm.yml
  when:
    - "omc_cloudagent_oracle_asm_entities is defined"
    - "omc_cloudagent_oracle_asm_entities|length > 0"
- name: "Deploying to any runing Oracle databases on"
  include_tasks: db.yml
  when:
    - "omc_cloudagent_oracle_db_entities is defined"
    - "omc_cloudagent_oracle_db_entities|length > 0"
- name: "Generating JSON files for monitored entities & credentials"
  include_tasks: entity-deploy.yml
