---
# tasks file for oracle-omc-cloudagent
- name: Set facts about installation
  include_tasks: facts.yml
- name: configure OS prerequisites
  include_tasks: os.yml
- name: configure OS level
  include_tasks: user.yml
- name: fetch cloud image
  include_tasks: fetch.yml
- name: install agent
  include_tasks: install.yml
- name: execute post-installation steps
  include_tasks: post-install.yml
- name: execute database steps
  include_tasks: db-deploy.yml
  when:
    - "omc_cloudagent_databases_monitored is defined"
- name: add entitity credentials
  include_tasks: add-entity-creds.yml
  when:
    - "omc_cloudagent_credentials is defined"
